FROM mcr.microsoft.com/azure-cli

# TODO
# install all dependencies
# install cloud provider CLI
# use proper CLI commands to deply the app
#RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash
RUN az webapp up --name simple-flask-rest-api --location westeurope --sku F1 --dryrun

# azure secret:    ZoG8Q~pIVRVfYdXJJXdEniJ9-MLmGJ5yayIChcqr
# azure secret ID: 4af353dc-9c86-4e7b-b327-3d66f18bdf03
