FROM mcr.microsoft.com/azure-cli

# TODO
# install all dependencies
# install cloud provider CLI
# use proper CLI commands to deply the app
#RUN curl -sL https://aka.ms/InstallAzureCLIDeb | sh
#RUN az login --service-principal -u 4af353dc-9c86-4e7b-b327-3d66f18bdf03 -p ZoG8Q~pIVRVfYdXJJXdEniJ9-MLmGJ5yayIChcqr --tenant b6607980-e520-465c-a392-892bf3674fbb
#RUN az webapp up --name simple-flask-rest-api --location westeurope --sku F1 --dryrun
COPY ./dist/ /app

# azure secret:    ZoG8Q~pIVRVfYdXJJXdEniJ9-MLmGJ5yayIChcqr
# azure secret ID: 4af353dc-9c86-4e7b-b327-3d66f18bdf03
# azure tenant ID: b6607980-e520-465c-a392-892bf3674fbb
